version: '3'

services:

  mongos:
    container_name: mongos
    image: mongo
    command: mongos --configdb cfgrs/172.30.0.3:27017,172.30.0.4:27017,172.30.0.2:27017 --bind_ip 0.0.0.0 --port 27017
    ports:
      - 30000:27017
    networks:
      - proxy-net

networks:
  proxy-net:
    external:
      name: mongodb-network
